{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "51FPMElM8M4b",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "outputId": "46c70718-26e5-4325-de62-8074353f19bb"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: torchmetrics in /usr/local/lib/python3.10/dist-packages (1.6.0)\n",
            "Requirement already satisfied: numpy>1.20.0 in /usr/local/lib/python3.10/dist-packages (from torchmetrics) (1.26.4)\n",
            "Requirement already satisfied: packaging>17.1 in /usr/local/lib/python3.10/dist-packages (from torchmetrics) (24.2)\n",
            "Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from torchmetrics) (2.5.0+cu121)\n",
            "Requirement already satisfied: lightning-utilities>=0.8.0 in /usr/local/lib/python3.10/dist-packages (from torchmetrics) (0.11.8)\n",
            "Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from lightning-utilities>=0.8.0->torchmetrics) (75.1.0)\n",
            "Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from lightning-utilities>=0.8.0->torchmetrics) (4.12.2)\n",
            "Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->torchmetrics) (3.16.1)\n",
            "Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->torchmetrics) (3.4.2)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->torchmetrics) (3.1.4)\n",
            "Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->torchmetrics) (2024.10.0)\n",
            "Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->torchmetrics) (1.13.1)\n",
            "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch>=2.0.0->torchmetrics) (1.3.0)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=2.0.0->torchmetrics) (3.0.2)\n"
          ]
        }
      ],
      "source": [
        "!pip install torchmetrics"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install ray[tune]"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "79m4uqq-kbO8",
        "outputId": "f3bb0b55-f4e3-48df-8f9a-83d4437789bf"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: ray[tune] in /usr/local/lib/python3.10/dist-packages (2.39.0)\n",
            "Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.10/dist-packages (from ray[tune]) (8.1.7)\n",
            "Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from ray[tune]) (3.16.1)\n",
            "Requirement already satisfied: jsonschema in /usr/local/lib/python3.10/dist-packages (from ray[tune]) (4.23.0)\n",
            "Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ray[tune]) (1.1.0)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from ray[tune]) (24.2)\n",
            "Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /usr/local/lib/python3.10/dist-packages (from ray[tune]) (4.25.5)\n",
            "Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from ray[tune]) (6.0.2)\n",
            "Requirement already satisfied: aiosignal in /usr/local/lib/python3.10/dist-packages (from ray[tune]) (1.3.1)\n",
            "Requirement already satisfied: frozenlist in /usr/local/lib/python3.10/dist-packages (from ray[tune]) (1.5.0)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from ray[tune]) (2.32.3)\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from ray[tune]) (2.2.2)\n",
            "Requirement already satisfied: tensorboardX>=1.9 in /usr/local/lib/python3.10/dist-packages (from ray[tune]) (2.6.2.2)\n",
            "Requirement already satisfied: pyarrow>=6.0.1 in /usr/local/lib/python3.10/dist-packages (from ray[tune]) (17.0.0)\n",
            "Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from ray[tune]) (2024.10.0)\n",
            "Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.10/dist-packages (from pyarrow>=6.0.1->ray[tune]) (1.26.4)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema->ray[tune]) (24.2.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema->ray[tune]) (2024.10.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema->ray[tune]) (0.35.1)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema->ray[tune]) (0.21.0)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->ray[tune]) (2.8.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->ray[tune]) (2024.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->ray[tune]) (2024.2)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->ray[tune]) (3.4.0)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->ray[tune]) (3.10)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->ray[tune]) (2.2.3)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->ray[tune]) (2024.8.30)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->ray[tune]) (1.16.0)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import io\n",
        "import ast\n",
        "import torch\n",
        "import pickle\n",
        "import numpy as np\n",
        "from PIL import Image\n",
        "\n",
        "import ray\n",
        "from ray import tune\n",
        "\n",
        "import torch.nn as nn\n",
        "import torch.optim as optim\n",
        "from torchvision import models\n",
        "import torch.nn.functional as F\n",
        "from torchvision import transforms\n",
        "from torch.utils.data import random_split, DataLoader, TensorDataset\n",
        "\n",
        "from torch.utils.tensorboard import SummaryWriter\n",
        "from torchmetrics.classification import MultilabelPrecision, MultilabelRecall, MultilabelF1Score"
      ],
      "metadata": {
        "id": "Ild_OD2ANy0b"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "ray.shutdown()\n",
        "ray.init(ignore_reinit_error=True)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 76
        },
        "id": "iUPiGxjwOyLy",
        "outputId": "f2e69f70-5dad-406e-9617-abb586b9c2ee"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2024-11-14 21:51:59,272\tINFO worker.py:1819 -- Started a local Ray instance.\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "RayContext(dashboard_url='', python_version='3.10.12', ray_version='2.39.0', ray_commit='5a6c33536df3f6ed5e987a169b82739bb7e3d80e')"
            ],
            "text/html": [
              "<div class=\"lm-Widget p-Widget lm-Panel p-Panel jp-Cell-outputWrapper\">\n",
              "    <div style=\"margin-left: 50px;display: flex;flex-direction: row;align-items: center\">\n",
              "        <div class=\"jp-RenderedHTMLCommon\" style=\"display: flex; flex-direction: row;\">\n",
              "  <svg viewBox=\"0 0 567 224\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" style=\"height: 3em;\">\n",
              "    <g clip-path=\"url(#clip0_4338_178347)\">\n",
              "        <path d=\"M341.29 165.561H355.29L330.13 129.051C345.63 123.991 354.21 112.051 354.21 94.2307C354.21 71.3707 338.72 58.1807 311.88 58.1807H271V165.561H283.27V131.661H311.8C314.25 131.661 316.71 131.501 319.01 131.351L341.25 165.561H341.29ZM283.29 119.851V70.0007H311.82C331.3 70.0007 342.34 78.2907 342.34 94.5507C342.34 111.271 331.34 119.861 311.82 119.861L283.29 119.851ZM451.4 138.411L463.4 165.561H476.74L428.74 58.1807H416L367.83 165.561H380.83L392.83 138.411H451.4ZM446.19 126.601H398L422 72.1407L446.24 126.601H446.19ZM526.11 128.741L566.91 58.1807H554.35L519.99 114.181L485.17 58.1807H472.44L514.01 129.181V165.541H526.13V128.741H526.11Z\" fill=\"var(--jp-ui-font-color0)\"/>\n",
              "        <path d=\"M82.35 104.44C84.0187 97.8827 87.8248 92.0678 93.1671 87.9146C98.5094 83.7614 105.083 81.5067 111.85 81.5067C118.617 81.5067 125.191 83.7614 130.533 87.9146C135.875 92.0678 139.681 97.8827 141.35 104.44H163.75C164.476 101.562 165.622 98.8057 167.15 96.2605L127.45 56.5605C121.071 60.3522 113.526 61.6823 106.235 60.3005C98.9443 58.9187 92.4094 54.9203 87.8602 49.0574C83.3109 43.1946 81.0609 35.8714 81.5332 28.4656C82.0056 21.0599 85.1679 14.0819 90.4252 8.8446C95.6824 3.60726 102.672 0.471508 110.08 0.0272655C117.487 -0.416977 124.802 1.86091 130.647 6.4324C136.493 11.0039 140.467 17.5539 141.821 24.8501C143.175 32.1463 141.816 39.6859 138 46.0505L177.69 85.7505C182.31 82.9877 187.58 81.4995 192.962 81.4375C198.345 81.3755 203.648 82.742 208.33 85.3976C213.012 88.0532 216.907 91.9029 219.616 96.5544C222.326 101.206 223.753 106.492 223.753 111.875C223.753 117.258 222.326 122.545 219.616 127.197C216.907 131.848 213.012 135.698 208.33 138.353C203.648 141.009 198.345 142.375 192.962 142.313C187.58 142.251 182.31 140.763 177.69 138L138 177.7C141.808 184.071 143.155 191.614 141.79 198.91C140.424 206.205 136.44 212.75 130.585 217.313C124.731 221.875 117.412 224.141 110.004 223.683C102.596 223.226 95.6103 220.077 90.3621 214.828C85.1139 209.58 81.9647 202.595 81.5072 195.187C81.0497 187.779 83.3154 180.459 87.878 174.605C92.4405 168.751 98.9853 164.766 106.281 163.401C113.576 162.035 121.119 163.383 127.49 167.19L167.19 127.49C165.664 124.941 164.518 122.182 163.79 119.3H141.39C139.721 125.858 135.915 131.673 130.573 135.826C125.231 139.98 118.657 142.234 111.89 142.234C105.123 142.234 98.5494 139.98 93.2071 135.826C87.8648 131.673 84.0587 125.858 82.39 119.3H60C58.1878 126.495 53.8086 132.78 47.6863 136.971C41.5641 141.163 34.1211 142.972 26.7579 142.059C19.3947 141.146 12.6191 137.574 7.70605 132.014C2.79302 126.454 0.0813599 119.29 0.0813599 111.87C0.0813599 104.451 2.79302 97.2871 7.70605 91.7272C12.6191 86.1673 19.3947 82.5947 26.7579 81.6817C34.1211 80.7686 41.5641 82.5781 47.6863 86.7696C53.8086 90.9611 58.1878 97.2456 60 104.44H82.35ZM100.86 204.32C103.407 206.868 106.759 208.453 110.345 208.806C113.93 209.159 117.527 208.258 120.522 206.256C123.517 204.254 125.725 201.276 126.771 197.828C127.816 194.38 127.633 190.677 126.253 187.349C124.874 184.021 122.383 181.274 119.205 179.577C116.027 177.88 112.359 177.337 108.826 178.042C105.293 178.746 102.113 180.654 99.8291 183.44C97.5451 186.226 96.2979 189.718 96.3 193.32C96.2985 195.364 96.7006 197.388 97.4831 199.275C98.2656 201.163 99.4132 202.877 100.86 204.32ZM204.32 122.88C206.868 120.333 208.453 116.981 208.806 113.396C209.159 109.811 208.258 106.214 206.256 103.219C204.254 100.223 201.275 98.0151 197.827 96.97C194.38 95.9249 190.676 96.1077 187.348 97.4873C184.02 98.8669 181.274 101.358 179.577 104.536C177.879 107.714 177.337 111.382 178.041 114.915C178.746 118.448 180.653 121.627 183.439 123.911C186.226 126.195 189.717 127.443 193.32 127.44C195.364 127.443 197.388 127.042 199.275 126.259C201.163 125.476 202.878 124.328 204.32 122.88ZM122.88 19.4205C120.333 16.8729 116.981 15.2876 113.395 14.9347C109.81 14.5817 106.213 15.483 103.218 17.4849C100.223 19.4868 98.0146 22.4654 96.9696 25.9131C95.9245 29.3608 96.1073 33.0642 97.4869 36.3922C98.8665 39.7202 101.358 42.4668 104.535 44.1639C107.713 45.861 111.381 46.4036 114.914 45.6992C118.447 44.9949 121.627 43.0871 123.911 40.301C126.195 37.515 127.442 34.0231 127.44 30.4205C127.44 28.3772 127.038 26.3539 126.255 24.4664C125.473 22.5788 124.326 20.8642 122.88 19.4205ZM19.42 100.86C16.8725 103.408 15.2872 106.76 14.9342 110.345C14.5813 113.93 15.4826 117.527 17.4844 120.522C19.4863 123.518 22.4649 125.726 25.9127 126.771C29.3604 127.816 33.0638 127.633 36.3918 126.254C39.7198 124.874 42.4664 122.383 44.1635 119.205C45.8606 116.027 46.4032 112.359 45.6988 108.826C44.9944 105.293 43.0866 102.114 40.3006 99.8296C37.5145 97.5455 34.0227 96.2983 30.42 96.3005C26.2938 96.3018 22.337 97.9421 19.42 100.86ZM100.86 100.86C98.3125 103.408 96.7272 106.76 96.3742 110.345C96.0213 113.93 96.9226 117.527 98.9244 120.522C100.926 123.518 103.905 125.726 107.353 126.771C110.8 127.816 114.504 127.633 117.832 126.254C121.16 124.874 123.906 122.383 125.604 119.205C127.301 116.027 127.843 112.359 127.139 108.826C126.434 105.293 124.527 102.114 121.741 99.8296C118.955 97.5455 115.463 96.2983 111.86 96.3005C109.817 96.299 107.793 96.701 105.905 97.4835C104.018 98.2661 102.303 99.4136 100.86 100.86Z\" fill=\"#00AEEF\"/>\n",
              "    </g>\n",
              "    <defs>\n",
              "        <clipPath id=\"clip0_4338_178347\">\n",
              "            <rect width=\"566.93\" height=\"223.75\" fill=\"white\"/>\n",
              "        </clipPath>\n",
              "    </defs>\n",
              "  </svg>\n",
              "</div>\n",
              "\n",
              "        <table class=\"jp-RenderedHTMLCommon\" style=\"border-collapse: collapse;color: var(--jp-ui-font-color1);font-size: var(--jp-ui-font-size1);\">\n",
              "    <tr>\n",
              "        <td style=\"text-align: left\"><b>Python version:</b></td>\n",
              "        <td style=\"text-align: left\"><b>3.10.12</b></td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "        <td style=\"text-align: left\"><b>Ray version:</b></td>\n",
              "        <td style=\"text-align: left\"><b>2.39.0</b></td>\n",
              "    </tr>\n",
              "    \n",
              "</table>\n",
              "\n",
              "    </div>\n",
              "</div>\n"
            ]
          },
          "metadata": {},
          "execution_count": 21
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "print(ray.cluster_resources())"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "CgQJia_YO00h",
        "outputId": "4e8e6134-a11c-4985-b57c-90953ade08a2"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "{'CPU': 2.0, 'object_store_memory': 4000217088.0, 'node:172.28.0.12': 1.0, 'memory': 8000434176.0, 'node:__internal_head__': 1.0}\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "@ray.remote\n",
        "def simple_task(x):\n",
        "    import time\n",
        "    time.sleep(2)  # Simulate work\n",
        "    return x * x\n",
        "\n",
        "# Run tasks in parallel\n",
        "results = ray.get([simple_task.remote(i) for i in range(10)])\n",
        "print(results)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "7fAglyjTRPsr",
        "outputId": "1abc1ec6-ac9d-4849-a7b0-591608b4d991"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "config = {\n",
        "    \"num_epochs\": tune.randint(5, 20),\n",
        "    \"batch_size\": tune.choice([16, 32, 64]),\n",
        "    \"learning_rate\": tune.loguniform(1e-6, 1e-3),\n",
        "    \"demographics_fc_size\": tune.choice([32, 64, 128]),\n",
        "    \"file_path\": \"/content/preprocessed_dummy_data.pkl\",\n",
        "    \"train_percent\": 0.7,\n",
        "    \"val_percent\": 0.1,\n",
        "    \"num_demographics\": 3,\n",
        "    \"num_classes\": 15,\n",
        "}"
      ],
      "metadata": {
        "id": "V1sCBz2zk6az"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "def load_data(original_data_pickle, batch_size, train_percent, val_percent, target_size=(224, 224)):\n",
        "    images = []\n",
        "    demographics = []\n",
        "    labels= []\n",
        "\n",
        "    resize_transform = transforms.Compose([\n",
        "        transforms.Resize(target_size),\n",
        "        transforms.ToTensor()\n",
        "    ])\n",
        "\n",
        "    with open(original_data_pickle, 'rb') as f:\n",
        "        data = pickle.load(f)\n",
        "\n",
        "    for item in data.values():\n",
        "\n",
        "      \"\"\"\n",
        "      The image data we get would be in bytes. We need to open it and convert it to grey scale and then resize. Recheck it. What are we doing with resizing before then?\n",
        "      \"\"\"\n",
        "      image_data = item['image_data']\n",
        "      image = Image.open(io.BytesIO(image_data)).convert('L')\n",
        "      image = resize_transform(image)  # Resizing and converting to tensor with shape (1, H, W) --> got an error without it\n",
        "\n",
        "      label= item['image_label']\n",
        "      label = ast.literal_eval(label)\n",
        "      label = np.array(label, dtype=int)\n",
        "\n",
        "      age = torch.tensor([item['age']], dtype=torch.float32)\n",
        "      gender = torch.tensor(item['gender'], dtype=torch.float32)\n",
        "\n",
        "      images.append(image)\n",
        "      demographics.append(torch.cat([age, gender]))\n",
        "      labels.append(label)\n",
        "\n",
        "    \"\"\"\n",
        "    Stacking images and demographics.\n",
        "    images Shape: (num_samples, channels, height, width)\n",
        "    demographics Shape: (num_samples, num_features)\n",
        "    \"\"\"\n",
        "    images = torch.stack(images)\n",
        "    demographics = torch.stack(demographics)\n",
        "    labels = torch.stack([torch.tensor(label, dtype=torch.long) for label in labels])\n",
        "    #labels = torch.tensor(labels, dtype= torch.long)\n",
        "\n",
        "    dataset = TensorDataset(images, demographics, labels)\n",
        "\n",
        "    train_size = int(train_percent * len(dataset))\n",
        "    val_size = int(val_percent * len(dataset))\n",
        "    test_size = len(dataset) - train_size - val_size\n",
        "\n",
        "    train_dataset, val_dataset, test_dataset = random_split(dataset, [train_size, val_size, test_size])\n",
        "\n",
        "    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)\n",
        "    val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)\n",
        "    test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)\n",
        "\n",
        "    print(f\"Training samples: {len(train_dataset)}, Validation samples: {len(val_dataset)}, Test samples: {len(test_dataset)}\")\n",
        "\n",
        "    return train_loader, val_loader, test_loader"
      ],
      "metadata": {
        "id": "2u446Niv8Vb2"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "train_loader, val_loader, test_loader= load_data(config['file_path'], 32, 0.7, 0.1)\n",
        "print(train_loader)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Pmf5Rwe_Yclx",
        "outputId": "57993481-411b-47af-bcff-7f3a2745d79b"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Training samples: 35, Validation samples: 5, Test samples: 10\n",
            "<torch.utils.data.dataloader.DataLoader object at 0x7c3d1de094b0>\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "class CustomResNet18(nn.Module):\n",
        "    def __init__(self, demographic_fc_size, num_demographics, num_classes=15):\n",
        "        super(CustomResNet18, self).__init__()\n",
        "\n",
        "        self.resnet = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)\n",
        "\n",
        "        # Modifying the first convolutional layer to accept grayscale images (1 channel) --> generally ResNet expects 3 channels\n",
        "        #for RGB\n",
        "        self.resnet.conv1 = nn.Conv2d(1, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)\n",
        "\n",
        "        # Removing the final fully connected layer in ResNet\n",
        "        self.resnet = nn.Sequential(*list(self.resnet.children())[:-1])\n",
        "\n",
        "        # this fc processes the demographics (age + gender)\n",
        "        self.demographics_fc = nn.Sequential(\n",
        "            nn.Linear(num_demographics, demographic_fc_size),\n",
        "            nn.ReLU(),\n",
        "            nn.Dropout(0.5)\n",
        "        )\n",
        "\n",
        "        self.fc = nn.Linear(512 + demographic_fc_size, num_classes)  # 512 from ResNet(it's how resnet is), 32 from demographics_fc, can make it 64?\n",
        "\n",
        "    def forward(self, images, demographics):\n",
        "        x = self.resnet(images)  # Passing images through the modified ResNet (without its last layer)\n",
        "        x = x.view(x.size(0), -1)  # Flattening the ResNet output\n",
        "\n",
        "        demographics_features = self.demographics_fc(demographics)\n",
        "        x = torch.cat((x, demographics_features), dim=1)\n",
        "\n",
        "        #print(\"Shape after concatenating demographics:\", x.shape)\n",
        "\n",
        "        x = self.fc(x)\n",
        "        #print(\"Output shape before returning:\", x.shape)\n",
        "\n",
        "        return x"
      ],
      "metadata": {
        "id": "CuJs5PPhPAoC"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
        "print(device)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "kL9i5Kh6UglU",
        "outputId": "3187d62a-506e-4020-a9a5-8f7cf3853690"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "cpu\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "writer = SummaryWriter(\"runs/CustomResNet18_experiment\")\n",
        "\n",
        "def freeze_unfreeze_layers(model, freeze=True, layers_to_train=[\"layer4\", \"fc\"]):\n",
        "    for name, param in model.named_parameters():\n",
        "        if any(layer in name for layer in layers_to_train):\n",
        "            param.requires_grad = not freeze\n",
        "        else:\n",
        "            param.requires_grad = freeze\n",
        "\n",
        "@ray.remote\n",
        "def train_model(train_loader, val_loader, model, criterion, optimizer, num_epochs= 10):\n",
        "\n",
        "  model.train()\n",
        "\n",
        "  best_val_accuracy = 0\n",
        "  for epoch in range(num_epochs):\n",
        "    running_loss = 0.0\n",
        "    for inputs, demographics, labels in train_loader:\n",
        "      inputs, demographics, labels = inputs.to(device), demographics.to(device), labels.to(device)\n",
        "\n",
        "      # Repeating grayscale images to make them 3 channels - this is not needed now since I changed the ResNet to accept grayscale,\n",
        "      #in-general ResNet expects RGB images ig\n",
        "\n",
        "      #inputs = inputs.repeat(1, 3, 1, 1)\n",
        "\n",
        "      optimizer.zero_grad()\n",
        "\n",
        "      outputs = model(inputs, demographics)\n",
        "      loss = criterion(outputs, labels.float())\n",
        "\n",
        "      loss.backward()\n",
        "      optimizer.step()\n",
        "\n",
        "      running_loss += loss.item()\n",
        "\n",
        "    avg_train_loss = running_loss / len(train_loader)\n",
        "    #writer.add_scalar(\"Loss/Train\", avg_train_loss, epoch)\n",
        "\n",
        "\n",
        "    model.eval()\n",
        "    val_loss = 0.0\n",
        "    correct = 0\n",
        "    total = 0\n",
        "    with torch.no_grad():\n",
        "      for inputs, demographics, labels in val_loader:\n",
        "        inputs, demographics, labels = inputs.to(device), demographics.to(device), labels.to(device)\n",
        "        outputs = model(inputs, demographics)\n",
        "\n",
        "        val_loss += criterion(outputs, labels.float()).item()\n",
        "        probabilities = torch.sigmoid(outputs)\n",
        "        predicted = (probabilities >= 0.5).int()\n",
        "\n",
        "        correct += (predicted == labels).sum().item()\n",
        "        total += labels.numel()\n",
        "\n",
        "    avg_val_loss = val_loss / len(val_loader)\n",
        "    val_accuracy = 100 * correct / total\n",
        "    \"\"\"writer.add_scalar(\"Loss/Validation\", avg_val_loss, epoch)\n",
        "    writer.add_scalar(\"Accuracy/Validation\", val_accuracy, epoch)\"\"\"\n",
        "\n",
        "    if val_accuracy > best_val_accuracy:\n",
        "      best_val_accuracy = val_accuracy\n",
        "\n",
        "    print(f\"Epoch {epoch+1}/{num_epochs}, Training Loss: {avg_train_loss}, Validation Loss: {avg_val_loss}, Validation Accuracy: {val_accuracy}%\")\n",
        "\n",
        "  return best_val_accuracy"
      ],
      "metadata": {
        "id": "sg1GtW1Z8dWX"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "def evaluate_model(test_loader, model, criterion, precision_metric, recall_metric, f1_metric, confidence= 0.3):\n",
        "    model.eval()\n",
        "    correct = 0\n",
        "    total = 0\n",
        "    test_loss = 0.0\n",
        "\n",
        "    precision_metric.reset()\n",
        "    recall_metric.reset()\n",
        "    f1_metric.reset()\n",
        "\n",
        "    with torch.no_grad():\n",
        "      for inputs, demographics, labels in test_loader:\n",
        "        inputs, demographics, labels = inputs.to(device), demographics.to(device), labels.to(device)\n",
        "        outputs = model(inputs, demographics)\n",
        "\n",
        "        test_loss += criterion(outputs, labels.float()).item()\n",
        "\n",
        "        probabilities = torch.sigmoid(outputs)\n",
        "        predicted = (probabilities >= confidence).int()\n",
        "\n",
        "        correct += (predicted == labels).sum().item()\n",
        "        total += labels.numel()\n",
        "\n",
        "        #print(\"predicted:\", predicted)\n",
        "        #print(\"labels: \", labels)\n",
        "\n",
        "        precision_metric.update(predicted, labels)\n",
        "        recall_metric.update(predicted, labels)\n",
        "        f1_metric.update(predicted, labels)\n",
        "\n",
        "    test_accuracy = 100 * correct / total\n",
        "    precision = precision_metric.compute().item()\n",
        "    recall = recall_metric.compute().item()\n",
        "    f1_score = f1_metric.compute().item()\n",
        "    avg_test_loss = test_loss / len(test_loader)\n",
        "\n",
        "    \"\"\"writer.add_scalar(\"Loss/Test\", avg_test_loss)\n",
        "    writer.add_scalar(\"Accuracy/Test\", test_accuracy)\n",
        "    writer.add_scalar(\"Precision/Test\", precision)\n",
        "    writer.add_scalar(\"Recall/Test\", recall)\n",
        "    writer.add_scalar(\"F1-Score/Test\", f1_score)\"\"\"\n",
        "\n",
        "    print(f'Test Loss: {avg_test_loss:.4f}')\n",
        "    print(f'Test Accuracy: {test_accuracy:.2f}%')\n",
        "    print(f'Test Precision: {precision:.4f}, Recall: {recall:.4f}, F1-score: {f1_score:.4f}')"
      ],
      "metadata": {
        "id": "vV4_0dnN8r4I"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "def objective(config):\n",
        "    \"\"\"num_epochs = trial.suggest_int(\"num_epochs\", 5, 20)\n",
        "    batch_size = trial.suggest_categorical(\"batch_size\", [16, 32, 64])\n",
        "    learning_rate = trial.suggest_loguniform(\"learning_rate\", 1e-6, 1e-3)\n",
        "    demographics_fc_size = trial.suggest_int(\"demographics_size\", 32, 64, 128)\"\"\"\n",
        "\n",
        "    num_epochs = config[\"num_epochs\"]\n",
        "    batch_size = config[\"batch_size\"]\n",
        "    learning_rate = config[\"learning_rate\"]\n",
        "    demographics_fc_size = config[\"demographics_fc_size\"]\n",
        "\n",
        "    train_loader, val_loader, test_loader = load_data(config[\"file_path\"], batch_size, config[\"train_percent\"], config[\"val_percent\"])\n",
        "\n",
        "    model = CustomResNet18(demographics_fc_size, num_demographics=config[\"num_demographics\"], num_classes=config[\"num_classes\"]).to(device)\n",
        "    freeze_unfreeze_layers(model, freeze=True, layers_to_train=[\"layer4\", \"fc\"])\n",
        "\n",
        "    optimizer = optim.Adam(model.parameters(), lr=learning_rate)\n",
        "    criterion = nn.BCEWithLogitsLoss()\n",
        "\n",
        "    best_val_accuracy_future = train_model.remote(train_loader, val_loader, model, criterion, optimizer, num_epochs)\n",
        "\n",
        "    # Retrieve the result (best_val_accuracy) using ray.get()\n",
        "    best_val_accuracy = ray.get(best_val_accuracy_future)\n",
        "\n",
        "    #best_val_accuracy= ray.get(train_model(train_loader, val_loader, model, criterion, optimizer, num_epochs))\n",
        "\n",
        "    tune.report(best_val_accuracy=best_val_accuracy)"
      ],
      "metadata": {
        "id": "S1T8XsMihqaK"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "num_samples= 10\n",
        "#resources_per_trial = tune.PlacementGroupFactory([{'CPU': 1.0}]*num_samples)\n",
        "\n",
        "analysis = tune.run(\n",
        "    objective,\n",
        "    config= config,\n",
        "    resources_per_trial={\"cpu\": 1, \"gpu\": 0},\n",
        "    num_samples= num_samples,\n",
        "    metric=\"best_val_accuracy\",\n",
        "    mode=\"max\"\n",
        ")\n",
        "\n",
        "best_trial = analysis.best_trial\n",
        "print(\"Best trial:\", best_trial)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "T903Z9Sbj8Un",
        "outputId": "de40c429-da92-4e5c-bcf2-c7e045d656e4"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "+------------------------------------------------------------------+\n",
            "| Configuration for experiment     objective_2024-11-14_21-52-27   |\n",
            "+------------------------------------------------------------------+\n",
            "| Search algorithm                 BasicVariantGenerator           |\n",
            "| Scheduler                        FIFOScheduler                   |\n",
            "| Number of trials                 10                              |\n",
            "+------------------------------------------------------------------+\n",
            "\n",
            "View detailed results here: /root/ray_results/objective_2024-11-14_21-52-27\n",
            "To visualize your results with TensorBoard, run: `tensorboard --logdir /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts`\n",
            "\n",
            "Trial status: 10 PENDING\n",
            "Current time: 2024-11-14 21:52:27. Total running time: 0s\n",
            "Logical resource usage: 2.0/2 CPUs, 0/0 GPUs\n",
            "+-----------------------------------------------------------------------------------------------------------+\n",
            "| Trial name              status       num_epochs     batch_size     learning_rate     demographics_fc_size |\n",
            "+-----------------------------------------------------------------------------------------------------------+\n",
            "| objective_bd322_00000   PENDING               8             64       2.43862e-05                       64 |\n",
            "| objective_bd322_00001   PENDING               7             16       0.000621034                      128 |\n",
            "| objective_bd322_00002   PENDING              13             64       5.25482e-05                      128 |\n",
            "| objective_bd322_00003   PENDING              12             64       1.27334e-05                       64 |\n",
            "| objective_bd322_00004   PENDING              19             16       0.000194263                       64 |\n",
            "| objective_bd322_00005   PENDING              16             32       0.000865804                       32 |\n",
            "| objective_bd322_00006   PENDING              12             32       0.000411324                       64 |\n",
            "| objective_bd322_00007   PENDING               7             16       1.53666e-06                      128 |\n",
            "| objective_bd322_00008   PENDING              16             64       0.000395811                       32 |\n",
            "| objective_bd322_00009   PENDING              16             64       2.73746e-05                      128 |\n",
            "+-----------------------------------------------------------------------------------------------------------+\n",
            "\n",
            "Trial objective_bd322_00000 started with configuration:\n",
            "+-------------------------------------------------------------+\n",
            "| Trial objective_bd322_00000 config                          |\n",
            "+-------------------------------------------------------------+\n",
            "| batch_size                                               64 |\n",
            "| demographics_fc_size                                     64 |\n",
            "| file_path                              ...ed_dummy_data.pkl |\n",
            "| learning_rate                                       0.00002 |\n",
            "| num_classes                                              15 |\n",
            "| num_demographics                                          3 |\n",
            "| num_epochs                                                8 |\n",
            "| train_percent                                           0.7 |\n",
            "| val_percent                                             0.1 |\n",
            "+-------------------------------------------------------------+\n",
            "\u001b[36m(objective pid=12679)\u001b[0m Training samples: 35, Validation samples: 5, Test samples: 10\n",
            "\n",
            "Trial objective_bd322_00001 started with configuration:\n",
            "+-------------------------------------------------------------+\n",
            "| Trial objective_bd322_00001 config                          |\n",
            "+-------------------------------------------------------------+\n",
            "| batch_size                                               16 |\n",
            "| demographics_fc_size                                    128 |\n",
            "| file_path                              ...ed_dummy_data.pkl |\n",
            "| learning_rate                                       0.00062 |\n",
            "| num_classes                                              15 |\n",
            "| num_demographics                                          3 |\n",
            "| num_epochs                                                7 |\n",
            "| train_percent                                           0.7 |\n",
            "| val_percent                                             0.1 |\n",
            "+-------------------------------------------------------------+\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2024-11-14 21:52:39,671\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_bd322_00000\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
            "    result = ray.get(future)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 2753, in get\n",
            "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 904, in get_objects\n",
            "    raise value.as_instanceof_cause()\n",
            "ray.exceptions.RayTaskError(RuntimeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=12679, ip=172.28.0.12, actor_id=13de4702f5777b92b0c8510e01000000, repr=objective)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
            "    raise skipped from exception_cause(skipped)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/_internal/util.py\", line 104, in run\n",
            "    self._ret = self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
            "    training_func=lambda: self._trainable_func(self.config),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 250, in _trainable_func\n",
            "    output = fn()\n",
            "  File \"<ipython-input-24-61796a6f0982>\", line 20, in objective\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 139, in _remote_proxy\n",
            "    return self._remote(args=args, kwargs=kwargs, **self._default_options)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 416, in _remote\n",
            "    _task_launch_hook(self._function_descriptor, resources, scheduling_strategy)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/train/_internal/session.py\", line 557, in _tune_task_and_actor_launch_hook\n",
            "    raise RuntimeError(\n",
            "RuntimeError: No trial resources are available for launching the task `__main__.train_model`. To resolve this, specify the Tune option:\n",
            "\n",
            ">  resources_per_trial=tune.PlacementGroupFactory(\n",
            ">    [{'CPU': 1.0}] + [{'CPU': 1.0}] * N\n",
            ">  )\n",
            "\n",
            "Where `N` is the number of slots to reserve for trial tasks. If you are using a Ray training library, there might be a utility function to set this automatically for you. For more information, refer to https://docs.ray.io/en/latest/tune/tutorials/tune-resources.html\n",
            "2024-11-14 21:52:39,757\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_bd322_00001\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
            "    result = ray.get(future)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 2753, in get\n",
            "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 904, in get_objects\n",
            "    raise value.as_instanceof_cause()\n",
            "ray.exceptions.RayTaskError(RuntimeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=12678, ip=172.28.0.12, actor_id=b834cce00b7383add890699f01000000, repr=objective)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
            "    raise skipped from exception_cause(skipped)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/_internal/util.py\", line 104, in run\n",
            "    self._ret = self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
            "    training_func=lambda: self._trainable_func(self.config),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 250, in _trainable_func\n",
            "    output = fn()\n",
            "  File \"<ipython-input-24-61796a6f0982>\", line 20, in objective\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 139, in _remote_proxy\n",
            "    return self._remote(args=args, kwargs=kwargs, **self._default_options)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 416, in _remote\n",
            "    _task_launch_hook(self._function_descriptor, resources, scheduling_strategy)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/train/_internal/session.py\", line 557, in _tune_task_and_actor_launch_hook\n",
            "    raise RuntimeError(\n",
            "RuntimeError: No trial resources are available for launching the task `__main__.train_model`. To resolve this, specify the Tune option:\n",
            "\n",
            ">  resources_per_trial=tune.PlacementGroupFactory(\n",
            ">    [{'CPU': 1.0}] + [{'CPU': 1.0}] * N\n",
            ">  )\n",
            "\n",
            "Where `N` is the number of slots to reserve for trial tasks. If you are using a Ray training library, there might be a utility function to set this automatically for you. For more information, refer to https://docs.ray.io/en/latest/tune/tutorials/tune-resources.html\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Trial objective_bd322_00000 errored after 0 iterations at 2024-11-14 21:52:39. Total running time: 12s\n",
            "Error file: /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00000_0_batch_size=64,demographics_fc_size=64,learning_rate=0.0000,num_epochs=8_2024-11-14_21-52-27/error.txt\n",
            "\n",
            "Trial objective_bd322_00001 errored after 0 iterations at 2024-11-14 21:52:39. Total running time: 12s\n",
            "Error file: /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00001_1_batch_size=16,demographics_fc_size=128,learning_rate=0.0006,num_epochs=7_2024-11-14_21-52-27/error.txt\n",
            "\n",
            "Trial objective_bd322_00003 started with configuration:\n",
            "+-------------------------------------------------------------+\n",
            "| Trial objective_bd322_00003 config                          |\n",
            "+-------------------------------------------------------------+\n",
            "| batch_size                                               64 |\n",
            "| demographics_fc_size                                     64 |\n",
            "| file_path                              ...ed_dummy_data.pkl |\n",
            "| learning_rate                                       0.00001 |\n",
            "| num_classes                                              15 |\n",
            "| num_demographics                                          3 |\n",
            "| num_epochs                                               12 |\n",
            "| train_percent                                           0.7 |\n",
            "| val_percent                                             0.1 |\n",
            "+-------------------------------------------------------------+\n",
            "\u001b[36m(objective pid=12875)\u001b[0m Training samples: 35, Validation samples: 5, Test samples: 10\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
            "\n",
            "Trial objective_bd322_00002 started with configuration:\n",
            "+-------------------------------------------------------------+\n",
            "| Trial objective_bd322_00002 config                          |\n",
            "+-------------------------------------------------------------+\n",
            "| batch_size                                               64 |\n",
            "| demographics_fc_size                                    128 |\n",
            "| file_path                              ...ed_dummy_data.pkl |\n",
            "| learning_rate                                       0.00005 |\n",
            "| num_classes                                              15 |\n",
            "| num_demographics                                          3 |\n",
            "| num_epochs                                               13 |\n",
            "| train_percent                                           0.7 |\n",
            "| val_percent                                             0.1 |\n",
            "+-------------------------------------------------------------+\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2024-11-14 21:52:53,290\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_bd322_00003\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
            "    result = ray.get(future)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 2753, in get\n",
            "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 904, in get_objects\n",
            "    raise value.as_instanceof_cause()\n",
            "ray.exceptions.RayTaskError(RuntimeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=12875, ip=172.28.0.12, actor_id=39037210836f113174441f4001000000, repr=objective)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
            "    raise skipped from exception_cause(skipped)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/_internal/util.py\", line 104, in run\n",
            "    self._ret = self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
            "    training_func=lambda: self._trainable_func(self.config),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 250, in _trainable_func\n",
            "    output = fn()\n",
            "  File \"<ipython-input-24-61796a6f0982>\", line 20, in objective\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 139, in _remote_proxy\n",
            "    return self._remote(args=args, kwargs=kwargs, **self._default_options)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 416, in _remote\n",
            "    _task_launch_hook(self._function_descriptor, resources, scheduling_strategy)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/train/_internal/session.py\", line 557, in _tune_task_and_actor_launch_hook\n",
            "    raise RuntimeError(\n",
            "RuntimeError: No trial resources are available for launching the task `__main__.train_model`. To resolve this, specify the Tune option:\n",
            "\n",
            ">  resources_per_trial=tune.PlacementGroupFactory(\n",
            ">    [{'CPU': 1.0}] + [{'CPU': 1.0}] * N\n",
            ">  )\n",
            "\n",
            "Where `N` is the number of slots to reserve for trial tasks. If you are using a Ray training library, there might be a utility function to set this automatically for you. For more information, refer to https://docs.ray.io/en/latest/tune/tutorials/tune-resources.html\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Trial objective_bd322_00003 errored after 0 iterations at 2024-11-14 21:52:53. Total running time: 26s\n",
            "Error file: /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00003_3_batch_size=64,demographics_fc_size=64,learning_rate=0.0000,num_epochs=12_2024-11-14_21-52-27/error.txt\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2024-11-14 21:52:53,583\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_bd322_00002\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
            "    result = ray.get(future)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 2753, in get\n",
            "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 904, in get_objects\n",
            "    raise value.as_instanceof_cause()\n",
            "ray.exceptions.RayTaskError(RuntimeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=12874, ip=172.28.0.12, actor_id=1eee528dece87d49a068222a01000000, repr=objective)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
            "    raise skipped from exception_cause(skipped)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/_internal/util.py\", line 104, in run\n",
            "    self._ret = self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
            "    training_func=lambda: self._trainable_func(self.config),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 250, in _trainable_func\n",
            "    output = fn()\n",
            "  File \"<ipython-input-24-61796a6f0982>\", line 20, in objective\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 139, in _remote_proxy\n",
            "    return self._remote(args=args, kwargs=kwargs, **self._default_options)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 416, in _remote\n",
            "    _task_launch_hook(self._function_descriptor, resources, scheduling_strategy)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/train/_internal/session.py\", line 557, in _tune_task_and_actor_launch_hook\n",
            "    raise RuntimeError(\n",
            "RuntimeError: No trial resources are available for launching the task `__main__.train_model`. To resolve this, specify the Tune option:\n",
            "\n",
            ">  resources_per_trial=tune.PlacementGroupFactory(\n",
            ">    [{'CPU': 1.0}] + [{'CPU': 1.0}] * N\n",
            ">  )\n",
            "\n",
            "Where `N` is the number of slots to reserve for trial tasks. If you are using a Ray training library, there might be a utility function to set this automatically for you. For more information, refer to https://docs.ray.io/en/latest/tune/tutorials/tune-resources.html\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Trial objective_bd322_00002 errored after 0 iterations at 2024-11-14 21:52:53. Total running time: 26s\n",
            "Error file: /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00002_2_batch_size=64,demographics_fc_size=128,learning_rate=0.0001,num_epochs=13_2024-11-14_21-52-27/error.txt\n",
            "\n",
            "Trial status: 4 ERROR | 6 PENDING\n",
            "Current time: 2024-11-14 21:52:57. Total running time: 30s\n",
            "Logical resource usage: 2.0/2 CPUs, 0/0 GPUs\n",
            "+-----------------------------------------------------------------------------------------------------------+\n",
            "| Trial name              status       num_epochs     batch_size     learning_rate     demographics_fc_size |\n",
            "+-----------------------------------------------------------------------------------------------------------+\n",
            "| objective_bd322_00004   PENDING              19             16       0.000194263                       64 |\n",
            "| objective_bd322_00005   PENDING              16             32       0.000865804                       32 |\n",
            "| objective_bd322_00006   PENDING              12             32       0.000411324                       64 |\n",
            "| objective_bd322_00007   PENDING               7             16       1.53666e-06                      128 |\n",
            "| objective_bd322_00008   PENDING              16             64       0.000395811                       32 |\n",
            "| objective_bd322_00009   PENDING              16             64       2.73746e-05                      128 |\n",
            "| objective_bd322_00000   ERROR                 8             64       2.43862e-05                       64 |\n",
            "| objective_bd322_00001   ERROR                 7             16       0.000621034                      128 |\n",
            "| objective_bd322_00002   ERROR                13             64       5.25482e-05                      128 |\n",
            "| objective_bd322_00003   ERROR                12             64       1.27334e-05                       64 |\n",
            "+-----------------------------------------------------------------------------------------------------------+\n",
            "\n",
            "Trial objective_bd322_00004 started with configuration:\n",
            "+-------------------------------------------------------------+\n",
            "| Trial objective_bd322_00004 config                          |\n",
            "+-------------------------------------------------------------+\n",
            "| batch_size                                               16 |\n",
            "| demographics_fc_size                                     64 |\n",
            "| file_path                              ...ed_dummy_data.pkl |\n",
            "| learning_rate                                       0.00019 |\n",
            "| num_classes                                              15 |\n",
            "| num_demographics                                          3 |\n",
            "| num_epochs                                               19 |\n",
            "| train_percent                                           0.7 |\n",
            "| val_percent                                             0.1 |\n",
            "+-------------------------------------------------------------+\n",
            "\u001b[36m(objective pid=13034)\u001b[0m Training samples: 35, Validation samples: 5, Test samples: 10\u001b[32m [repeated 2x across cluster]\u001b[0m\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2024-11-14 21:53:06,450\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_bd322_00004\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
            "    result = ray.get(future)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 2753, in get\n",
            "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 904, in get_objects\n",
            "    raise value.as_instanceof_cause()\n",
            "ray.exceptions.RayTaskError(RuntimeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=13034, ip=172.28.0.12, actor_id=8ca1c10c2d49816da14d833801000000, repr=objective)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
            "    raise skipped from exception_cause(skipped)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/_internal/util.py\", line 104, in run\n",
            "    self._ret = self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
            "    training_func=lambda: self._trainable_func(self.config),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 250, in _trainable_func\n",
            "    output = fn()\n",
            "  File \"<ipython-input-24-61796a6f0982>\", line 20, in objective\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 139, in _remote_proxy\n",
            "    return self._remote(args=args, kwargs=kwargs, **self._default_options)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 416, in _remote\n",
            "    _task_launch_hook(self._function_descriptor, resources, scheduling_strategy)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/train/_internal/session.py\", line 557, in _tune_task_and_actor_launch_hook\n",
            "    raise RuntimeError(\n",
            "RuntimeError: No trial resources are available for launching the task `__main__.train_model`. To resolve this, specify the Tune option:\n",
            "\n",
            ">  resources_per_trial=tune.PlacementGroupFactory(\n",
            ">    [{'CPU': 1.0}] + [{'CPU': 1.0}] * N\n",
            ">  )\n",
            "\n",
            "Where `N` is the number of slots to reserve for trial tasks. If you are using a Ray training library, there might be a utility function to set this automatically for you. For more information, refer to https://docs.ray.io/en/latest/tune/tutorials/tune-resources.html\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Trial objective_bd322_00004 errored after 0 iterations at 2024-11-14 21:53:06. Total running time: 39s\n",
            "Error file: /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00004_4_batch_size=16,demographics_fc_size=64,learning_rate=0.0002,num_epochs=19_2024-11-14_21-52-27/error.txt\n",
            "\n",
            "Trial objective_bd322_00005 started with configuration:\n",
            "+-------------------------------------------------------------+\n",
            "| Trial objective_bd322_00005 config                          |\n",
            "+-------------------------------------------------------------+\n",
            "| batch_size                                               32 |\n",
            "| demographics_fc_size                                     32 |\n",
            "| file_path                              ...ed_dummy_data.pkl |\n",
            "| learning_rate                                       0.00087 |\n",
            "| num_classes                                              15 |\n",
            "| num_demographics                                          3 |\n",
            "| num_epochs                                               16 |\n",
            "| train_percent                                           0.7 |\n",
            "| val_percent                                             0.1 |\n",
            "+-------------------------------------------------------------+\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2024-11-14 21:53:07,199\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_bd322_00005\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
            "    result = ray.get(future)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 2753, in get\n",
            "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 904, in get_objects\n",
            "    raise value.as_instanceof_cause()\n",
            "ray.exceptions.RayTaskError(RuntimeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=13042, ip=172.28.0.12, actor_id=309ce6384b041c817df47b7f01000000, repr=objective)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
            "    raise skipped from exception_cause(skipped)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/_internal/util.py\", line 104, in run\n",
            "    self._ret = self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
            "    training_func=lambda: self._trainable_func(self.config),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 250, in _trainable_func\n",
            "    output = fn()\n",
            "  File \"<ipython-input-24-61796a6f0982>\", line 20, in objective\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 139, in _remote_proxy\n",
            "    return self._remote(args=args, kwargs=kwargs, **self._default_options)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 416, in _remote\n",
            "    _task_launch_hook(self._function_descriptor, resources, scheduling_strategy)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/train/_internal/session.py\", line 557, in _tune_task_and_actor_launch_hook\n",
            "    raise RuntimeError(\n",
            "RuntimeError: No trial resources are available for launching the task `__main__.train_model`. To resolve this, specify the Tune option:\n",
            "\n",
            ">  resources_per_trial=tune.PlacementGroupFactory(\n",
            ">    [{'CPU': 1.0}] + [{'CPU': 1.0}] * N\n",
            ">  )\n",
            "\n",
            "Where `N` is the number of slots to reserve for trial tasks. If you are using a Ray training library, there might be a utility function to set this automatically for you. For more information, refer to https://docs.ray.io/en/latest/tune/tutorials/tune-resources.html\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Trial objective_bd322_00005 errored after 0 iterations at 2024-11-14 21:53:07. Total running time: 39s\n",
            "Error file: /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00005_5_batch_size=32,demographics_fc_size=32,learning_rate=0.0009,num_epochs=16_2024-11-14_21-52-27/error.txt\n",
            "\n",
            "Trial objective_bd322_00006 started with configuration:\n",
            "+-------------------------------------------------------------+\n",
            "| Trial objective_bd322_00006 config                          |\n",
            "+-------------------------------------------------------------+\n",
            "| batch_size                                               32 |\n",
            "| demographics_fc_size                                     64 |\n",
            "| file_path                              ...ed_dummy_data.pkl |\n",
            "| learning_rate                                       0.00041 |\n",
            "| num_classes                                              15 |\n",
            "| num_demographics                                          3 |\n",
            "| num_epochs                                               12 |\n",
            "| train_percent                                           0.7 |\n",
            "| val_percent                                             0.1 |\n",
            "+-------------------------------------------------------------+\n",
            "\u001b[36m(objective pid=13229)\u001b[0m Training samples: 35, Validation samples: 5, Test samples: 10\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
            "\n",
            "Trial objective_bd322_00007 started with configuration:\n",
            "+-------------------------------------------------------------+\n",
            "| Trial objective_bd322_00007 config                          |\n",
            "+-------------------------------------------------------------+\n",
            "| batch_size                                               16 |\n",
            "| demographics_fc_size                                    128 |\n",
            "| file_path                              ...ed_dummy_data.pkl |\n",
            "| learning_rate                                            0. |\n",
            "| num_classes                                              15 |\n",
            "| num_demographics                                          3 |\n",
            "| num_epochs                                                7 |\n",
            "| train_percent                                           0.7 |\n",
            "| val_percent                                             0.1 |\n",
            "+-------------------------------------------------------------+\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2024-11-14 21:53:21,673\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_bd322_00006\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
            "    result = ray.get(future)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 2753, in get\n",
            "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 904, in get_objects\n",
            "    raise value.as_instanceof_cause()\n",
            "ray.exceptions.RayTaskError(RuntimeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=13229, ip=172.28.0.12, actor_id=b03468f2e19291f81ac41e4b01000000, repr=objective)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
            "    raise skipped from exception_cause(skipped)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/_internal/util.py\", line 104, in run\n",
            "    self._ret = self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
            "    training_func=lambda: self._trainable_func(self.config),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 250, in _trainable_func\n",
            "    output = fn()\n",
            "  File \"<ipython-input-24-61796a6f0982>\", line 20, in objective\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 139, in _remote_proxy\n",
            "    return self._remote(args=args, kwargs=kwargs, **self._default_options)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 416, in _remote\n",
            "    _task_launch_hook(self._function_descriptor, resources, scheduling_strategy)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/train/_internal/session.py\", line 557, in _tune_task_and_actor_launch_hook\n",
            "    raise RuntimeError(\n",
            "RuntimeError: No trial resources are available for launching the task `__main__.train_model`. To resolve this, specify the Tune option:\n",
            "\n",
            ">  resources_per_trial=tune.PlacementGroupFactory(\n",
            ">    [{'CPU': 1.0}] + [{'CPU': 1.0}] * N\n",
            ">  )\n",
            "\n",
            "Where `N` is the number of slots to reserve for trial tasks. If you are using a Ray training library, there might be a utility function to set this automatically for you. For more information, refer to https://docs.ray.io/en/latest/tune/tutorials/tune-resources.html\n",
            "2024-11-14 21:53:21,707\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_bd322_00007\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
            "    result = ray.get(future)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 2753, in get\n",
            "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 904, in get_objects\n",
            "    raise value.as_instanceof_cause()\n",
            "ray.exceptions.RayTaskError(RuntimeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=13231, ip=172.28.0.12, actor_id=333ceeae58fa538b53c4843f01000000, repr=objective)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
            "    raise skipped from exception_cause(skipped)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/_internal/util.py\", line 104, in run\n",
            "    self._ret = self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
            "    training_func=lambda: self._trainable_func(self.config),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 250, in _trainable_func\n",
            "    output = fn()\n",
            "  File \"<ipython-input-24-61796a6f0982>\", line 20, in objective\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 139, in _remote_proxy\n",
            "    return self._remote(args=args, kwargs=kwargs, **self._default_options)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 416, in _remote\n",
            "    _task_launch_hook(self._function_descriptor, resources, scheduling_strategy)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/train/_internal/session.py\", line 557, in _tune_task_and_actor_launch_hook\n",
            "    raise RuntimeError(\n",
            "RuntimeError: No trial resources are available for launching the task `__main__.train_model`. To resolve this, specify the Tune option:\n",
            "\n",
            ">  resources_per_trial=tune.PlacementGroupFactory(\n",
            ">    [{'CPU': 1.0}] + [{'CPU': 1.0}] * N\n",
            ">  )\n",
            "\n",
            "Where `N` is the number of slots to reserve for trial tasks. If you are using a Ray training library, there might be a utility function to set this automatically for you. For more information, refer to https://docs.ray.io/en/latest/tune/tutorials/tune-resources.html\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Trial objective_bd322_00006 errored after 0 iterations at 2024-11-14 21:53:21. Total running time: 54s\n",
            "Error file: /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00006_6_batch_size=32,demographics_fc_size=64,learning_rate=0.0004,num_epochs=12_2024-11-14_21-52-27/error.txt\n",
            "\n",
            "Trial objective_bd322_00007 errored after 0 iterations at 2024-11-14 21:53:21. Total running time: 54s\n",
            "Error file: /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00007_7_batch_size=16,demographics_fc_size=128,learning_rate=0.0000,num_epochs=7_2024-11-14_21-52-27/error.txt\n",
            "\n",
            "Trial status: 8 ERROR | 2 PENDING\n",
            "Current time: 2024-11-14 21:53:27. Total running time: 1min 0s\n",
            "Logical resource usage: 2.0/2 CPUs, 0/0 GPUs\n",
            "+-----------------------------------------------------------------------------------------------------------+\n",
            "| Trial name              status       num_epochs     batch_size     learning_rate     demographics_fc_size |\n",
            "+-----------------------------------------------------------------------------------------------------------+\n",
            "| objective_bd322_00008   PENDING              16             64       0.000395811                       32 |\n",
            "| objective_bd322_00009   PENDING              16             64       2.73746e-05                      128 |\n",
            "| objective_bd322_00000   ERROR                 8             64       2.43862e-05                       64 |\n",
            "| objective_bd322_00001   ERROR                 7             16       0.000621034                      128 |\n",
            "| objective_bd322_00002   ERROR                13             64       5.25482e-05                      128 |\n",
            "| objective_bd322_00003   ERROR                12             64       1.27334e-05                       64 |\n",
            "| objective_bd322_00004   ERROR                19             16       0.000194263                       64 |\n",
            "| objective_bd322_00005   ERROR                16             32       0.000865804                       32 |\n",
            "| objective_bd322_00006   ERROR                12             32       0.000411324                       64 |\n",
            "| objective_bd322_00007   ERROR                 7             16       1.53666e-06                      128 |\n",
            "+-----------------------------------------------------------------------------------------------------------+\n",
            "\n",
            "Trial objective_bd322_00009 started with configuration:\n",
            "+-------------------------------------------------------------+\n",
            "| Trial objective_bd322_00009 config                          |\n",
            "+-------------------------------------------------------------+\n",
            "| batch_size                                               64 |\n",
            "| demographics_fc_size                                    128 |\n",
            "| file_path                              ...ed_dummy_data.pkl |\n",
            "| learning_rate                                       0.00003 |\n",
            "| num_classes                                              15 |\n",
            "| num_demographics                                          3 |\n",
            "| num_epochs                                               16 |\n",
            "| train_percent                                           0.7 |\n",
            "| val_percent                                             0.1 |\n",
            "+-------------------------------------------------------------+\n",
            "\n",
            "Trial objective_bd322_00008 started with configuration:\n",
            "+-------------------------------------------------------------+\n",
            "| Trial objective_bd322_00008 config                          |\n",
            "+-------------------------------------------------------------+\n",
            "| batch_size                                               64 |\n",
            "| demographics_fc_size                                     32 |\n",
            "| file_path                              ...ed_dummy_data.pkl |\n",
            "| learning_rate                                        0.0004 |\n",
            "| num_classes                                              15 |\n",
            "| num_demographics                                          3 |\n",
            "| num_epochs                                               16 |\n",
            "| train_percent                                           0.7 |\n",
            "| val_percent                                             0.1 |\n",
            "+-------------------------------------------------------------+\n",
            "\u001b[36m(objective pid=13430)\u001b[0m Training samples: 35, Validation samples: 5, Test samples: 10\u001b[32m [repeated 2x across cluster]\u001b[0m\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2024-11-14 21:53:35,401\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_bd322_00009\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
            "    result = ray.get(future)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 2753, in get\n",
            "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 904, in get_objects\n",
            "    raise value.as_instanceof_cause()\n",
            "ray.exceptions.RayTaskError(RuntimeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=13430, ip=172.28.0.12, actor_id=59d1bf2c1f8b3d20fa8bf7b001000000, repr=objective)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
            "    raise skipped from exception_cause(skipped)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/_internal/util.py\", line 104, in run\n",
            "    self._ret = self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
            "    training_func=lambda: self._trainable_func(self.config),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 250, in _trainable_func\n",
            "    output = fn()\n",
            "  File \"<ipython-input-24-61796a6f0982>\", line 20, in objective\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 139, in _remote_proxy\n",
            "    return self._remote(args=args, kwargs=kwargs, **self._default_options)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 416, in _remote\n",
            "    _task_launch_hook(self._function_descriptor, resources, scheduling_strategy)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/train/_internal/session.py\", line 557, in _tune_task_and_actor_launch_hook\n",
            "    raise RuntimeError(\n",
            "RuntimeError: No trial resources are available for launching the task `__main__.train_model`. To resolve this, specify the Tune option:\n",
            "\n",
            ">  resources_per_trial=tune.PlacementGroupFactory(\n",
            ">    [{'CPU': 1.0}] + [{'CPU': 1.0}] * N\n",
            ">  )\n",
            "\n",
            "Where `N` is the number of slots to reserve for trial tasks. If you are using a Ray training library, there might be a utility function to set this automatically for you. For more information, refer to https://docs.ray.io/en/latest/tune/tutorials/tune-resources.html\n",
            "2024-11-14 21:53:35,481\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_bd322_00008\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
            "    result = ray.get(future)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 2753, in get\n",
            "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py\", line 904, in get_objects\n",
            "    raise value.as_instanceof_cause()\n",
            "ray.exceptions.RayTaskError(RuntimeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=13428, ip=172.28.0.12, actor_id=08355e63d9c9b0211ebef23d01000000, repr=objective)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
            "    raise skipped from exception_cause(skipped)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/air/_internal/util.py\", line 104, in run\n",
            "    self._ret = self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
            "    training_func=lambda: self._trainable_func(self.config),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/function_trainable.py\", line 250, in _trainable_func\n",
            "    output = fn()\n",
            "  File \"<ipython-input-24-61796a6f0982>\", line 20, in objective\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 139, in _remote_proxy\n",
            "    return self._remote(args=args, kwargs=kwargs, **self._default_options)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/remote_function.py\", line 416, in _remote\n",
            "    _task_launch_hook(self._function_descriptor, resources, scheduling_strategy)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/ray/train/_internal/session.py\", line 557, in _tune_task_and_actor_launch_hook\n",
            "    raise RuntimeError(\n",
            "RuntimeError: No trial resources are available for launching the task `__main__.train_model`. To resolve this, specify the Tune option:\n",
            "\n",
            ">  resources_per_trial=tune.PlacementGroupFactory(\n",
            ">    [{'CPU': 1.0}] + [{'CPU': 1.0}] * N\n",
            ">  )\n",
            "\n",
            "Where `N` is the number of slots to reserve for trial tasks. If you are using a Ray training library, there might be a utility function to set this automatically for you. For more information, refer to https://docs.ray.io/en/latest/tune/tutorials/tune-resources.html\n",
            "2024-11-14 21:53:35,511\tINFO tune.py:1009 -- Wrote the latest version of all result files and experiment state to '/root/ray_results/objective_2024-11-14_21-52-27' in 0.0206s.\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Trial objective_bd322_00009 errored after 0 iterations at 2024-11-14 21:53:35. Total running time: 1min 8s\n",
            "Error file: /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00009_9_batch_size=64,demographics_fc_size=128,learning_rate=0.0000,num_epochs=16_2024-11-14_21-52-27/error.txt\n",
            "\n",
            "Trial objective_bd322_00008 errored after 0 iterations at 2024-11-14 21:53:35. Total running time: 1min 8s\n",
            "Error file: /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00008_8_batch_size=64,demographics_fc_size=32,learning_rate=0.0004,num_epochs=16_2024-11-14_21-52-27/error.txt\n",
            "\n",
            "Trial status: 10 ERROR\n",
            "Current time: 2024-11-14 21:53:35. Total running time: 1min 8s\n",
            "Logical resource usage: 1.0/2 CPUs, 0/0 GPUs\n",
            "+-----------------------------------------------------------------------------------------------------------+\n",
            "| Trial name              status       num_epochs     batch_size     learning_rate     demographics_fc_size |\n",
            "+-----------------------------------------------------------------------------------------------------------+\n",
            "| objective_bd322_00000   ERROR                 8             64       2.43862e-05                       64 |\n",
            "| objective_bd322_00001   ERROR                 7             16       0.000621034                      128 |\n",
            "| objective_bd322_00002   ERROR                13             64       5.25482e-05                      128 |\n",
            "| objective_bd322_00003   ERROR                12             64       1.27334e-05                       64 |\n",
            "| objective_bd322_00004   ERROR                19             16       0.000194263                       64 |\n",
            "| objective_bd322_00005   ERROR                16             32       0.000865804                       32 |\n",
            "| objective_bd322_00006   ERROR                12             32       0.000411324                       64 |\n",
            "| objective_bd322_00007   ERROR                 7             16       1.53666e-06                      128 |\n",
            "| objective_bd322_00008   ERROR                16             64       0.000395811                       32 |\n",
            "| objective_bd322_00009   ERROR                16             64       2.73746e-05                      128 |\n",
            "+-----------------------------------------------------------------------------------------------------------+\n",
            "\n",
            "Number of errored trials: 10\n",
            "+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n",
            "| Trial name                # failures   error file                                                                                                                                                                                                                                                    |\n",
            "+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n",
            "| objective_bd322_00000              1   /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00000_0_batch_size=64,demographics_fc_size=64,learning_rate=0.0000,num_epochs=8_2024-11-14_21-52-27/error.txt   |\n",
            "| objective_bd322_00001              1   /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00001_1_batch_size=16,demographics_fc_size=128,learning_rate=0.0006,num_epochs=7_2024-11-14_21-52-27/error.txt  |\n",
            "| objective_bd322_00002              1   /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00002_2_batch_size=64,demographics_fc_size=128,learning_rate=0.0001,num_epochs=13_2024-11-14_21-52-27/error.txt |\n",
            "| objective_bd322_00003              1   /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00003_3_batch_size=64,demographics_fc_size=64,learning_rate=0.0000,num_epochs=12_2024-11-14_21-52-27/error.txt  |\n",
            "| objective_bd322_00004              1   /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00004_4_batch_size=16,demographics_fc_size=64,learning_rate=0.0002,num_epochs=19_2024-11-14_21-52-27/error.txt  |\n",
            "| objective_bd322_00005              1   /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00005_5_batch_size=32,demographics_fc_size=32,learning_rate=0.0009,num_epochs=16_2024-11-14_21-52-27/error.txt  |\n",
            "| objective_bd322_00006              1   /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00006_6_batch_size=32,demographics_fc_size=64,learning_rate=0.0004,num_epochs=12_2024-11-14_21-52-27/error.txt  |\n",
            "| objective_bd322_00007              1   /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00007_7_batch_size=16,demographics_fc_size=128,learning_rate=0.0000,num_epochs=7_2024-11-14_21-52-27/error.txt  |\n",
            "| objective_bd322_00008              1   /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00008_8_batch_size=64,demographics_fc_size=32,learning_rate=0.0004,num_epochs=16_2024-11-14_21-52-27/error.txt  |\n",
            "| objective_bd322_00009              1   /tmp/ray/session_2024-11-14_21-51-56_342513_5340/artifacts/2024-11-14_21-52-27/objective_2024-11-14_21-52-27/driver_artifacts/objective_bd322_00009_9_batch_size=64,demographics_fc_size=128,learning_rate=0.0000,num_epochs=16_2024-11-14_21-52-27/error.txt |\n",
            "+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n",
            "\n"
          ]
        },
        {
          "output_type": "error",
          "ename": "TuneError",
          "evalue": "('Trials did not complete', [objective_bd322_00000, objective_bd322_00001, objective_bd322_00002, objective_bd322_00003, objective_bd322_00004, objective_bd322_00005, objective_bd322_00006, objective_bd322_00007, objective_bd322_00008, objective_bd322_00009])",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mTuneError\u001b[0m                                 Traceback (most recent call last)",
            "\u001b[0;32m<ipython-input-25-c043ec5c9d48>\u001b[0m in \u001b[0;36m<cell line: 4>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mresources_per_trial\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtune\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mPlacementGroupFactory\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m{\u001b[0m\u001b[0;34m'CPU'\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;36m1.0\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0mnum_samples\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m analysis = tune.run(\n\u001b[0m\u001b[1;32m      5\u001b[0m     \u001b[0mobjective\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m     \u001b[0mconfig\u001b[0m\u001b[0;34m=\u001b[0m \u001b[0mconfig\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;32m/usr/local/lib/python3.10/dist-packages/ray/tune/tune.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, storage_path, storage_filesystem, search_alg, scheduler, checkpoint_config, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, resume, resume_config, reuse_actors, raise_on_failed_trial, callbacks, max_concurrent_trials, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, chdir_to_trial_dir, local_dir, _remote, _remote_string_queue, _entrypoint)\u001b[0m\n\u001b[1;32m   1033\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1034\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mraise_on_failed_trial\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mexperiment_interrupted_event\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mis_set\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1035\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mTuneError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Trials did not complete\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1036\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1037\u001b[0m             \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0merror\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Trials did not complete: %s\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mTuneError\u001b[0m: ('Trials did not complete', [objective_bd322_00000, objective_bd322_00001, objective_bd322_00002, objective_bd322_00003, objective_bd322_00004, objective_bd322_00005, objective_bd322_00006, objective_bd322_00007, objective_bd322_00008, objective_bd322_00009])"
          ]
        }
      ]
    }
  ]
}